[[headers]]
  for = "*.js" # js files should be set this way
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.css" # css files too
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.min.css" # css files too
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=31536000"